Algoritmo "ParouImparProcedimento"
//  
//  


Var
n : inteiro

procedimento parouimpar (V: inteiro)

inicio
   escreval (" O valor de V e ", V)
   escreval (" O valor de N e ", n)
   se (V%2 = 0) entao
      escreval (" O número", V, " é par")
      senao
      escreval (" O número", V, " é impar")
      fimse
fimprocedimento

Inicio

escreva ("Digite um número:  ")
leia(n)
parouimpar(n)
 escreval (" O valor de V e ", V)
 escreval (" O valor de N e ", n)


Fimalgoritmo